name: Update Blog Posts in README
on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC
  workflow_dispatch: # Allows manual trigger from GitHub Actions tab
  push:
    branches:
      - main # Runs on pushes to the main branch
permissions:
  contents: write # Required to commit changes to README.md
jobs:
  update-readme-blog-posts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x' # Use any Python 3 version
      - name: Install dependencies
        run: pip install requests beautifulsoup4 lxml # Add lxml here
      - name: Run script to update README
        run: python update_readme.py
        env:
          BLOG_FEED_URL: "https://davidgao7.github.io/index.xml" # Your blog's RSS feed URL
      - name: Commit and push changes
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add README.md # Stage changes made by the Python script
          git commit -m "Draft: Update README with blog posts" || echo "No changes to commit (draft)" # Commit the local changes
          git pull --rebase origin main # Now pull and rebase
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
