name: Update Blog Feed From Hugo
on:
  schedule: # Run workflow automatically
    - cron: '0 0 * * *' # Run once per day
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly
  push:
    branches:
      - main # run on main branch push
jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub Metrics for Blog
      - uses: actions/checkout@v4
      - uses: sarisia/actions-readme-feed@v1
        with:
          url: 'https://davidgao7.github.io/index.xml'
          file: 'README.md'
      - uses: sarisia/actions-commit@master
